<?php
// C:\xampp\htdocs\IYO_Smart_Pantry\api\food_add.php
require_once __DIR__ . '/config.php';

$d = json_input();

// basic validation
$need = ['foodName','quantity','expiryDate','userID','categoryID','unitID'];
foreach ($need as $k) {
  if (!isset($d[$k]) || $d[$k] === '') {
    respond(['ok'=>false,'error'=>"Missing $k"], 400);
  }
}

// compute flags
$is_expiryStatus = (strtotime($d['expiryDate']) < strtotime('today')) ? 1 : 0;
$is_plan = !empty($d['is_plan']) ? 1 : 0;

// insert (foodID is generated by a DB trigger; do NOT send it yourself)
$sql = "INSERT INTO foods
  (foodName, quantity, expiryDate, is_expiryStatus, is_plan, storageLocation, remark, userID, categoryID, unitID)
  VALUES (:foodName, :quantity, :expiryDate, :is_expiryStatus, :is_plan, :storageLocation, :remark, :userID, :categoryID, :unitID)";

try {
  $stmt = $pdo->prepare($sql);
  $stmt->execute([
    ':foodName'        => $d['foodName'],
    ':quantity'        => $d['quantity'],
    ':expiryDate'      => $d['expiryDate'],       // YYYY-MM-DD
    ':is_expiryStatus' => $is_expiryStatus,
    ':is_plan'         => $is_plan,
    ':storageLocation' => $d['storageLocation'] ?? '',
    ':remark'          => $d['remark'] ?? '',
    ':userID'          => $d['userID'],
    ':categoryID'      => $d['categoryID'],
    ':unitID'          => $d['unitID'],
  ]);

  // The trigger produces a PK like "F123"; there is no auto-increment ID.
  // Grab the latest row for this user (order by the numeric part DESC). Not fully concurrency-safe, but sufficient here.
  $q = $pdo->prepare("SELECT foodID FROM foods WHERE userID = :uid ORDER BY CAST(SUBSTRING(foodID,2) AS UNSIGNED) DESC LIMIT 1");
  $q->execute([':uid' => $d['userID']]);
  $row = $q->fetch();

  respond(['ok'=>true, 'foodID'=>$row['foodID'] ?? null]);
} catch (Throwable $e) {
  // For debugging, you can log the error: error_log($e->getMessage());
  respond(['ok'=>false,'error'=>'DB error'], 500);
}
